#! /bin/sh
# WM BSPWM
sxhkd &
~/.fehbg &
conky -c $HOME/bin/.conky/rss &
compton -c -t-5 -l-5 -r3 -C &
export GDK_SCALE=2 &
export GDK_DPI_SCALE=0.4 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Blender desktop='^4' state=floating follow=on
bspc rule -a Brackets desktop='^3' state=floating follow=off
bspc rule -a Luakit desktop='^2'
bspc rule -a URxvt state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
