#!/bin/bash
sxhkd &
urxvt &
bspc monitor -d I II III IV V VI
bspc config border_width		1
bspc config window_gap			8
bspc config top_padding 		2
bspc config bottom_padding		2
bspc config split_ratio			0.44
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		false
bspc config history_aware_focus		true
bspc config focus_follows_pointer	true
bpsc config pointer_follows_focus	false
bspc config click_to_focus		false
bspc config adaptive raise		true
bspc config center_pseudo_tiled		true
bspc config focused_border_color 	"#000000"
bspc config normal_border_color		"#9ff88a"
bspc rule -a URxvt follow=on
bspc rule -a qutebrowser desktop='^2' state=floating
bspc rule -a Tor desktop='^3' state=floating
bspc rule -a Code desktop='^4' state=floating
bspc rule -a GitKraken desktop='^4' follow=on
