#!/usr/bin/env bash
echo -e '
              \e[0m\e[30m|               |               |               |               |\e[0m
   \e[31m█     █\e[0m    \e[30m|\e[0m    \e[32m█     █\e[0m    \e[30m|\e[0m    \e[33m█     █\e[0m    \e[30m|\e[0m    \e[34m█     █\e[0m    \e[30m|\e[0m    \e[35m█     █\e[0m    \e[30m|\e[0m    \e[36m█     █\e[0m
   \e[31m███████\e[0m    \e[30m|\e[0m    \e[32m███████\e[0m    \e[30m|\e[0m    \e[33m███████\e[0m    \e[30m|\e[0m    \e[34m███████\e[0m    \e[30m|\e[0m    \e[35m███████\e[0m    \e[30m|\e[0m    \e[36m███████\e[0m
 \e[31m███\e[1m\e[41m██\e[0m\e[31m█\e[1m\e[41m██\e[0m\e[31m███\e[0m  \e[30m|\e[0m  \e[32m███\e[1m\e[42m██\e[0m\e[32m█\e[1m\e[42m██\e[0m\e[32m███\e[0m  \e[30m|\e[0m  \e[33m███\e[1m\e[43m██\e[0m\e[33m█\e[1m\e[43m██\e[0m\e[33m███\e[0m  \e[30m|\e[0m  \e[34m███\e[1m\e[44m██\e[0m\e[34m█\e[1m\e[44m██\e[0m\e[34m███\e[0m  \e[30m|\e[0m  \e[35m███\e[1m\e[45m██\e[0m\e[35m█\e[1m\e[45m██\e[0m\e[35m███\e[0m  \e[30m|\e[0m  \e[36m███\e[1m\e[46m██\e[0m\e[36m█\e[1m\e[46m██\e[0m\e[36m███\e[0m
  \e[31m████\e[1m\e[41m█\e[0m\e[31m████\e[0m   \e[30m|\e[0m   \e[32m████\e[1m\e[42m█\e[0m\e[32m████\e[0m   \e[30m|\e[0m   \e[33m████\e[1m\e[43m█\e[0m\e[33m████\e[0m   \e[30m|\e[0m   \e[34m████\e[1m\e[44m█\e[0m\e[34m████\e[0m   \e[30m|\e[0m   \e[35m████\e[1m\e[45m█\e[0m\e[35m████\e[0m   \e[30m|\e[0m   \e[36m████\e[1m\e[46m█\e[0m\e[36m████\e[0m
  \e[31m█ █ \e[1m█\e[0m \e[31m█ █\e[0m   \e[30m|\e[0m   \e[32m█ █ \e[1m█\e[0m \e[32m█ █\e[0m   \e[30m|\e[0m   \e[33m█ █ \e[1m█\e[0m \e[33m█ █\e[0m   \e[30m|\e[0m   \e[34m█ █ \e[1m█\e[0m \e[34m█ █\e[0m   \e[30m|\e[0m   \e[35m█ █ \e[1m█\e[0m \e[35m█ █\e[0m   \e[30m|\e[0m   \e[36m█ █ \e[1m█\e[0m \e[36m█ █\e[0m
    \e[31m█   █\e[0m     \e[30m|\e[0m     \e[32m█   █\e[0m     \e[30m|\e[0m     \e[33m█   █\e[0m     \e[30m|\e[0m     \e[34m█   █\e[0m     \e[30m|\e[0m     \e[35m█   █\e[0m     \e[30m|\e[0m     \e[36m█   █\e[0m
              \e[30m|               |               |               |               |\e[0m
'
