#!/bin/sh
sxhkd &
urxvt -g 55x22 &
hsetroot -full /home/user/img/spider.jpg
compton --config /home/user/compton.conf &

bspc monitor -d I II III IV V
bspc config border_width         	1
bspc config window_gap          	12
bspc config top_padding			32
bspc config bottom_padding		32
bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance	 	false
bspc config history_aware_focus	 	true
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config click_to_focus		false
bspc config adapttive raise		true
bspc config center_pseudo_tiled		true
bpsc config normal_border_color		"#"
bpsc config focused_border_color	"#"
bspc config presel_feedback_color	"#"

bspc rule -a URxvt state=floating
bspc rule -a Luakit desktop='^3' state=floating follow=on
$HOME/.config/polybar/launch &
