#!/bin/sh

tint2 &
sxhkd &
~/.fehbg &
compton -c -t-5 -l-5 -r3 -o.48 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10
bspc config top_padding         68
bspc config left_padding        14
bspc config right_padding       14
bspc config bottom_padding      19

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config center_pseudo_tiled  true
bspc config focus_follows_poiter true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config normal_border_color   "#3f2654"
bspc config focus_border_color    "#291837"
bspc config presel_feedback_color "#291837"

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Luakit desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt:weechat desktop=^1 follow=on
bspc rule -a URxvt:tmux desktop=^1 follow=on
