#! /bin/sh
## Mono
sxhkd &
$HOME/.fehbg -C &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        	1
bspc config window_gap          	11
bspc config top_padding			4
bspc config left_padding		5
bspc config right_padding		5
bspc config bottom_padding		29

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bscp config focus_by_distance	 	false
bscp config history_aware_focus  	true
bscp config focus_follows_focus         true
bscp config pointer_follows_focus	false
bscp config click_to_focus		false
bscp config adaptive raise		true
bscp config center_pseudo_tiled		true

bspc rule -a Blender desktop='^4' state=floating follow=on
bspc rule -a Luakit desktop='^2'
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt state=floating
bspc rule -a URxvt:weechat desktop='^1' follow=on
bspc rule -a URxvt:pulsemixer state=floating
